name: Test Builds

on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

env:  
  NODE_VERSION: '20.x'                # set this to the node version to use
  NET_SDK_VERSION: '8.x'

permissions:
  contents: read

jobs:
  build-frontend-ng:  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3       
      - name: Use Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install NPM packages for bookstore        
        run: npm install --no-package-lock        
        working-directory: ${{ github.workspace }}/frontend/bookstore
      - name: Build frontend bookstore        
        working-directory: ${{ github.workspace }}/frontend/bookstore
        run: |        
          npm install
          npm run build --if-present
          npm run test --if-present
  
  build-frontend-react:  
          runs-on: ubuntu-latest
          steps:
            - uses: actions/checkout@v3       
            - name: Use Node.js
              uses: actions/setup-node@v4.0.0
              with:
                node-version: ${{ env.NODE_VERSION }}
            - name: Install NPM packages for bookstore        
              run: npm install --no-package-lock        
              working-directory: ${{ github.workspace }}/frontend/bookstore-react
            - name: Build frontend bookstore        
              working-directory: ${{ github.workspace }}/frontend/bookstore-react
              run: |        
                npm install
                npm run build --if-present
                npm run test --if-present
          
  build-backend:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     
     - name: Setup .NET SDK 
       uses: actions/setup-dotnet@v3.2.0     
       with:
         dotnet-version: ${{ env.NET_SDK_VERSION }}
         
     - name: Build Backend APIs
       working-directory: ${{ github.workspace }}/backend
       run: |         
         dotnet build          
      
